### ISSUE TITLE
Installed successfully but

### ISSUE THREAD

**Issue by ugintl** [X2Engine/X2Engine#190]
Installed the latest release successfully, but when I open single product page, it shows following error

```
Error 500
It looks like the application ran into an unexpected error.

We apologize for the inconvenience and would like to do our best to fix this issue. If you would like to make a post on our forums we can actively interact with you in getting this resolved. If not, simply sending the error report helps us immensely and will only improve the quality of the software. Thanks!
Send Error Report
Here's a quick list of what will be included in the report:

Error Code: 500
Error Message: CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'force.x2_actions.complete' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Stack Trace: [click to toggle display]
CDbException in C:\laragon\www\xcrm\protected\components\sortableWidget\SortableWidget.php(943)
#0 C:\laragon\www\xcrm\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\laragon\www\xcrm\protected\components\sortableWidget\recordViewWidgets\ActionHistoryChartWidget.php(124): CDbCommand->queryAll()
#2 C:\laragon\www\xcrm\protected\components\sortableWidget\recordViewWidgets\ActionHistoryChartWidget.php(305): ActionHistoryChartWidget::getChartData('1633666403', 1635608869, '5', 'product', NULL)
#3 C:\laragon\www\xcrm\protected\components\sortableWidget\recordViewWidgets\ActionHistoryChartWidget.php(142): ActionHistoryChartWidget->getInitialChartData('1633666403', '5', 'Product', NULL)
#4 C:\laragon\www\xcrm\framework\base\CComponent.php(111): ActionHistoryChartWidget->getSetupScript()
#5 C:\laragon\www\xcrm\protected\components\sortableWidget\SortableWidget.php(943): CComponent->__get('setupScript')
#6 C:\laragon\www\xcrm\protected\components\sortableWidget\SortableWidget.php(911): SortableWidget->renderWidgetContents()
#7 C:\laragon\www\xcrm\protected\components\sortableWidget\views\recordViewWidget.php(44): SortableWidget->renderWidget()
#8 C:\laragon\www\xcrm\framework\web\CBaseController.php(130): require('C:\\laragon\\www\\...')
#9 C:\laragon\www\xcrm\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\laragon\\www\\...', Array, false)
#10 C:\laragon\www\xcrm\protected\components\X2Widget.php(83): CBaseController->renderFile('C:\\laragon\\www\\...', Array, false)
#11 C:\laragon\www\xcrm\framework\web\widgets\CWidget.php(244): X2Widget->renderFile('C:\\laragon\\www\\...', Array, false)
#12 C:\laragon\www\xcrm\protected\components\sortableWidget\SortableWidget.php(1056): CWidget->render('application.com...', Array)
#13 C:\laragon\www\xcrm\protected\controllers\x2base.php(832): SortableWidget->run()
#14 C:\laragon\www\xcrm\protected\components\sortableWidget\SortableWidget.php(398): x2base->widget('application.com...', Array)
#15 C:\laragon\www\xcrm\protected\components\sortableWidget\RecordViewWidgetManager.php(126): SortableWidget::instantiateWidget('ActionHistoryCh...', Object(Profile), 'recordView', Array)
#16 C:\laragon\www\xcrm\protected\components\sortableWidget\views\_twoColumnSortableWidgetLayout.php(55): RecordViewWidgetManager->displayWidgets(1)
#17 C:\laragon\www\xcrm\framework\web\CBaseController.php(130): require('C:\\laragon\\www\\...')
#18 C:\laragon\www\xcrm\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\laragon\\www\\...', NULL, false)
#19 C:\laragon\www\xcrm\protected\components\X2Widget.php(83): CBaseController->renderFile('C:\\laragon\\www\\...', NULL, false)
#20 C:\laragon\www\xcrm\framework\web\widgets\CWidget.php(244): X2Widget->renderFile('C:\\laragon\\www\\...', NULL, false)
#21 C:\laragon\www\xcrm\protected\components\sortableWidget\TwoColumnSortableWidgetManager.php(110): CWidget->render('_twoColumnSorta...')
#22 C:\laragon\www\xcrm\protected\controllers\x2base.php(832): TwoColumnSortableWidgetManager->run()
#23 C:\laragon\www\xcrm\protected\components\X2WidgetList.php(81): x2base->widget('RecordViewWidge...', Array)
#24 C:\laragon\www\xcrm\protected\controllers\x2base.php(832): X2WidgetList->run()
#25 C:\laragon\www\xcrm\protected\modules\products\views\products\view.php(112): x2base->widget('X2WidgetList', Array)
#26 C:\laragon\www\xcrm\framework\web\CBaseController.php(126): require('C:\\laragon\\www\\...')
#27 C:\laragon\www\xcrm\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\laragon\\www\\...', Array, true)
#28 C:\laragon\www\xcrm\framework\web\CController.php(872): CBaseController->renderFile('C:\\laragon\\www\\...', Array, true)
#29 C:\laragon\www\xcrm\protected\controllers\x2base.php(731): CController->renderPartial('view', Array, true)
#30 C:\laragon\www\xcrm\protected\controllers\x2base.php(267): x2base->render('view', Array)
#31 C:\laragon\www\xcrm\protected\modules\products\controllers\ProductsController.php(92): x2base->view(Object(Product))
#32 [internal function]: ProductsController->actionView('5')
#33 C:\laragon\www\xcrm\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(ProductsController), Array)
#34 C:\laragon\www\xcrm\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProductsController), Object(ReflectionMethod), Array)
#35 C:\laragon\www\xcrm\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#36 C:\laragon\www\xcrm\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#37 C:\laragon\www\xcrm\protected\controllers\x2base.php(581): CFilterChain->run()
#38 C:\laragon\www\xcrm\framework\web\filters\CInlineFilter.php(58): x2base->filterSetPortlets(Object(CFilterChain))
#39 C:\laragon\www\xcrm\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#40 C:\laragon\www\xcrm\framework\web\filters\CFilter.php(40): CFilterChain->run()
#41 C:\laragon\www\xcrm\framework\web\filters\CFilterChain.php(131): CFilter->filter(Object(CFilterChain))
#42 C:\laragon\www\xcrm\framework\web\filters\CFilter.php(40): CFilterChain->run()
#43 C:\laragon\www\xcrm\framework\web\filters\CFilterChain.php(131): CFilter->filter(Object(CFilterChain))
#44 C:\laragon\www\xcrm\framework\web\CController.php(291): CFilterChain->run()
#45 C:\laragon\www\xcrm\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#46 C:\laragon\www\xcrm\framework\web\CWebApplication.php(282): CController->run('view')
#47 C:\laragon\www\xcrm\protected\components\X2WebApplication.php(65): CWebApplication->runController('products/produc...')
#48 C:\laragon\www\xcrm\framework\base\CApplication.php(185): X2WebApplication->processRequest()
#49 C:\laragon\www\xcrm\index.php(67): CApplication->run()
#50 {main}
X2Engine Version: 7.1
PHP Version: 7.4.15
```

**Comment by sotaspaso** [comment]
I had Error 500 on some pages. The issue was the PHP version.
X2CRM is working ok only on PHP 7.2 or lower versions.
Try switching to PHP 7.2

**Comment by ugintl** [comment]
@sotaspaso Still getting the error. If you see the error, it has something to do with mysql.  

`Error Message: CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'force.x2_actions.complete' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

I found a solution, but do not know how to implement it https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql

**Comment by ugintl** [comment]
I am getting this error on other pages as well

**Comment by ugintl** [comment]
@x2zulu Can you please look in to it?
